# Generated by Django 4.2.3 on 2023-07-07 06:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(choices=[('today', django.utils.timezone.now), ('tomarrow', datetime.datetime(2023, 7, 8, 6, 9, 18, 780339, tzinfo=datetime.timezone.utc))], verbose_name='date published'),
        ),
    ]
