# Generated by Django 4.2.3 on 2023-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0002_ward_patient_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='treats',
            field=models.ManyToManyField(to='medic.doctor'),
        ),
    ]
