# Generated by Django 4.2.3 on 2023-07-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0004_alter_patient_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='treats',
            new_name='treatedBy',
        ),
    ]
