# Generated by Django 4.2.3 on 2023-07-12 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0005_rename_treats_patient_treatedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='treatedBy',
            new_name='treated_by',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_admitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 12, 12, 52, 556862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_no',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.FileField(default=None, null=True, upload_to='patient_<django.db.models.fields.CharField>/'),
        ),
    ]
