# Generated by Django 4.2.3 on 2023-07-12 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0006_rename_treatedby_patient_treated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_admitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 12, 18, 55, 440033, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.FileField(default=None, null=True, upload_to='patient/<django.db.models.fields.CharField>/'),
        ),
    ]
