# Generated by Django 4.2.3 on 2023-07-12 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0013_alter_patient_date_admitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_admitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 12, 42, 0, 901771, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_no',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
