# Generated by Django 4.2.3 on 2023-07-13 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0014_alter_patient_date_admitted_alter_patient_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_no',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='company',
            field=models.CharField(default='Govt', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='ward',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_admitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 6, 38, 24, 683584, tzinfo=datetime.timezone.utc)),
        ),
    ]
