# Generated by Django 4.2.3 on 2023-07-13 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0016_receptionist_phone_no_alter_patient_date_admitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_admitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 6, 50, 53, 265862, tzinfo=datetime.timezone.utc)),
        ),
    ]
